### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by Kartikey1101** [MinhZou/selective-copying-mamba#1]
Traceback (most recent call last):
  File "/workspaces/selective-copying-mamba/selective_copying_mamba.py", line 6, in <module>
 from mamba_ssm.models.mixer_seq_simple import MambaLMHeadModel
ModuleNotFoundError: No module named 'mamba_ssm'

If try  after installing the original mamba model following parameters are not defined:
d_intermediate
attn_layer_idx
attn_cfg

**Comment by MinhZou** [comment]
Since the Mamba repository is continuously being updated, the initial version of this repository used the Mamba v1 model. For the latest models, you may need to make slight modifications to the code involving the Mamba model.

The parameters you mentioned, 'd_intermediate,' 'attn_layer_idx,' and 'attn_cfg,' do not exist in the version of Mamba that I have used.

**Comment by Kartikey1101** [comment]
Thanks for your response

Do you have a copy of the Mamba v1 model? I will be helpful for modification.

**Comment by MinhZou** [comment]
Sorry, I don't have a backup of Mamba v1. The source code has been heavily modified by me, and some of my important code cannot be open-sourced for the time being. I suggest you first get familiar with the official code by running it successfully, and then modify this code.
